terraform {
  required_providers {
    coder = {
      source = "coder/coder"
    }
    docker = {
      source = "kreuzwerker/docker"
    }
  }
}

locals {
  username = data.coder_workspace_owner.me.name

  # Workspace image with Node.js and the docker CLI preinstalled.
  # No nested daemon is used: the workspace talks to the host daemon
  # through a bind-mounted docker socket (Docker-outside-of-Docker).
  workspace_image = "codercom/enterprise-node:ubuntu"

  has_repo           = data.coder_parameter.repo_url.value != ""
  repo_folder        = try(module.git-clone[0].folder_name, "")
  workspace_folder   = local.has_repo ? "~/${local.repo_folder}" : "~"
  code_server_folder = local.has_repo ? "/home/coder/${local.repo_folder}" : "/home/coder"
}

# ------------------------------------------------------------------
# Docker daemon endpoint selection.
#
# LOCAL workspaces: leave docker_host empty (""). The provider falls
# back to the local Unix socket (/var/run/docker.sock) on the machine
# running the build — i.e. the Coder server's Docker daemon.
#
# REMOTE workspaces: set
#   docker_host     = "tcp://<tailscale-ip>:2376"
#   docker_ca       = contents of the remote's ca.pem
#   docker_cert     = contents of the remote's cert.pem
#   docker_key      = contents of the remote's key.pem
#
# The cert material is passed as PEM CONTENTS via these variables — no
# files need to be mounted into the Coder container. Marked sensitive so
# they're encrypted at rest and never shown in the UI.
# ------------------------------------------------------------------

variable "docker_host" {
  default     = ""
  description = "(Optional) Docker daemon URI. Empty = local Unix socket. Remote: tcp://<tailscale-ip>:2376"
  type        = string
}

variable "docker_ca" {
  default     = ""
  description = "(Remote only) Docker CA certificate PEM contents"
  type        = string
  sensitive   = true
}

variable "docker_cert" {
  default     = ""
  description = "(Remote only) Docker client certificate PEM contents"
  type        = string
  sensitive   = true
}

variable "docker_key" {
  default     = ""
  description = "(Remote only) Docker client private key PEM contents"
  type        = string
  sensitive   = true
}

# ------------------------------------------------------------------
# Workspace runtime (per-workspace choice).
#
# runsc = gVisor sandbox (default). Each workspace gets a user-space
# kernel boundary: syscalls are intercepted by the Sentry. No
# privileged mode, no nested daemons, no kernel modules.
#
# runc = plain container runtime. Use for workspaces that need an
# interactive TUI that is broken under gVisor (e.g. the opencode TUI
# never renders under gVisor — https://github.com/sst/opencode/issues/29802;
# headless `opencode run` works fine on runsc). The daemon must have
# the chosen runtime registered.
# ------------------------------------------------------------------

data "coder_parameter" "workspace_runtime" {
  type         = "string"
  name         = "workspace_runtime"
  display_name = "Workspace Runtime"
  description  = "runsc (gVisor sandbox) or runc (plain container). Choose runc if an interactive TUI fails to render under gVisor (e.g. opencode issue #29802)."
  default      = "runsc"
  mutable      = true

  validation {
    regex  = "^(runsc|runc)$"
    error  = "workspace_runtime must be 'runsc' or 'runc'."
  }
}

# ------------------------------------------------------------------
# Docker access inside the workspace (DooD over TLS).
#
# gVisor CANNOT relay connections through bind-mounted unix sockets, so
# the docker CLI in the workspace talks to the daemon over TLS instead:
#   DOCKER_HOST=tcp://<tailscale-ip>:2376
#   DOCKER_TLS_VERIFY=1, DOCKER_CERT_PATH=<mount point>
#
# The daemon's client certs (ca.pem/cert.pem/key.pem) must exist on the
# daemon host at docker_cert_dir; that directory is mounted read-only
# into the workspace. For the dind test layout this is /certs/client
# (generated by docker:dind); for a host daemon, stage the client certs
# at a host path (e.g. /home/josh/coder-tls/<remote>/).
# ------------------------------------------------------------------

variable "docker_cert_dir" {
  default     = "/certs/client"
  description = "Host path of the daemon's client TLS material (ca.pem, cert.pem, key.pem), mounted read-only into the workspace so the docker CLI can talk to the daemon over TLS (DooD)."
  type        = string
}

data "coder_parameter" "repo_url" {
  type         = "string"
  name         = "repo_url"
  display_name = "Git Repository"
  description  = "Enter the URL of a Git repository to clone. If provided, the workspace will clone it. Leave empty to skip cloning and work in the home directory."
  default      = ""
  mutable      = true
}

data "coder_parameter" "new_branch" {
  type         = "string"
  name         = "new_branch"
  display_name = "New Branch Name"
  description  = "Optional: after cloning, checkout or create this branch. If the branch does not exist, it will be created from HEAD."
  default      = ""
  mutable      = true
}

data "coder_parameter" "setup_command" {
  type         = "string"
  name         = "setup_command"
  display_name = "Setup Command"
  description  = "Optional: shell command run once on first workspace start to prepare the project - install dependencies, docker compose up services, seed demo data. Example: 'make dev' or './scripts/setup.sh'. Runs as the workspace user; docker works via the mounted daemon socket. Change this parameter to trigger a re-run on the next start."
  default      = ""
  mutable      = true
}

provider "docker" {
  host = var.docker_host != "" ? var.docker_host : null

  ca_material   = var.docker_ca != "" ? var.docker_ca : null
  cert_material = var.docker_cert != "" ? var.docker_cert : null
  key_material  = var.docker_key != "" ? var.docker_key : null
}

data "coder_provisioner" "me" {}
data "coder_workspace" "me" {}
data "coder_workspace_owner" "me" {}

resource "coder_agent" "main" {
  arch            = data.coder_provisioner.me.arch
  os              = "linux"
  dir             = local.workspace_folder
  startup_script  = <<-EOT
    set -e

    # Prepare user home with default files on first start.
    if [ ! -f ~/.init_done ]; then
      cp -rT /etc/skel ~
      touch ~/.init_done
    fi

    # Add any commands that should be executed at workspace startup
    # (e.g. install requirements, start a program, etc) here.
  EOT
  # NOTE: no shutdown_script by design. A previous version ran
  # `docker system prune -a -f` + `sudo service docker stop` at shutdown.
  # That is only safe while the workspace's docker CLI talks to its OWN
  # nested daemon. Once a host docker socket is mounted into workspaces
  # (DooD), a shutdown prune would wipe HOST containers/images
  # (Coolify, n8n, Ghost, Postgres, ...). Never run daemon-wide docker
  # cleanup from a workspace.

  # These environment variables allow you to make Git commits right away after creating a
  # workspace. Note that they take precedence over configuration defined in ~/.gitconfig!
  # You can remove this block if you'd prefer to configure Git manually or using
  # dotfiles. (see docs/dotfiles.md)
  #
  # In remote mode (docker_host set) the docker CLI is pointed at the
  # daemon over TLS (DooD) — gVisor cannot relay unix-socket connects,
  # so the socket mount does not work. Certs are mounted at
  # /certs/docker (see docker_cert_dir).
  env = merge(
    {
      GIT_AUTHOR_NAME     = coalesce(data.coder_workspace_owner.me.full_name, data.coder_workspace_owner.me.name)
      GIT_AUTHOR_EMAIL    = "${data.coder_workspace_owner.me.email}"
      GIT_COMMITTER_NAME  = coalesce(data.coder_workspace_owner.me.full_name, data.coder_workspace_owner.me.name)
      GIT_COMMITTER_EMAIL = "${data.coder_workspace_owner.me.email}"
    },
    var.docker_host != "" ? {
      DOCKER_HOST       = var.docker_host
      DOCKER_TLS_VERIFY = "1"
      DOCKER_CERT_PATH  = "/certs/docker"
    } : {}
  )

  # The following metadata blocks are optional. They are used to display
  # information about your workspace in the dashboard. You can remove them
  # if you don't want to display any information.
  metadata {
    display_name = "CPU Usage"
    key          = "0_cpu_usage"
    script       = "coder stat cpu"
    interval     = 10
    timeout      = 1
  }

  metadata {
    display_name = "RAM Usage"
    key          = "1_ram_usage"
    script       = "coder stat mem"
    interval     = 10
    timeout      = 1
  }

  metadata {
    display_name = "Home Disk"
    key          = "3_home_disk"
    script       = "coder stat disk --path $${HOME}"
    interval     = 60
    timeout      = 1
  }

  metadata {
    display_name = "CPU Usage (Host)"
    key          = "4_cpu_usage_host"
    script       = "coder stat cpu --host"
    interval     = 10
    timeout      = 1
  }

  metadata {
    display_name = "Memory Usage (Host)"
    key          = "5_mem_usage_host"
    script       = "coder stat mem --host"
    interval     = 10
    timeout      = 1
  }

  metadata {
    display_name = "Load Average (Host)"
    key          = "6_load_host"
    # get load avg scaled by number of cores
    script   = <<EOT
      echo "`cat /proc/loadavg | awk '{ print $1 }'` `nproc`" | awk '{ printf "%0.2f", $1/$2 }'
    EOT
    interval = 60
    timeout  = 1
  }

  metadata {
    display_name = "Swap Usage (Host)"
    key          = "7_swap_host"
    script       = <<EOT
      free -b | awk '/^Swap/ { printf("%.1f/%.1f", $3/1024.0/1024.0/1024.0, $2/1024.0/1024.0/1024.0) }'
    EOT
    interval     = 10
    timeout      = 1
  }
}

# See https://registry.coder.com/modules/coder/code-server
module "code-server" {
  count    = data.coder_workspace.me.start_count
  source   = "registry.coder.com/coder/code-server/coder"
  version  = "1.5.0"
  agent_id = coder_agent.main.id
  folder     = local.code_server_folder
  extensions = [
    "dracula-theme.theme-dracula"
  ]
}

# See https://registry.coder.com/modules/coder/git-clone
module "git-clone" {
  count    = data.coder_workspace.me.start_count * (local.has_repo ? 1 : 0)
  source   = "registry.coder.com/coder/git-clone/coder"
  agent_id = coder_agent.main.id
  url      = data.coder_parameter.repo_url.value
  base_dir = "~"
  # This ensures that the latest non-breaking version of the module gets
  # downloaded, you can also pin the module version to prevent breaking
  # changes in production.
  version = "~> 2.0"
}

# Enables git authentication for cloning PRIVATE repositories.
#
# Without this, cloning a private repo fails with:
#   fatal: unable to access 'https://github.com/<owner>/<repo>.git/':
#   The requested URL returned error: 403
# ("Write access to repository not granted").
#
# This requires a Git provider configured in Coder:
#   Admin -> External Auth -> "GitHub" -> enabled for this template.
# On first workspace start Coder then prompts the user to connect GitHub,
# and the git-clone module uses that token to clone.
#
# Leave the repo_url parameter EMPTY to skip cloning entirely (no prompt).
data "coder_external_auth" "github" {
  id = "github"
}

# One-time per-workspace project setup: runs the setup_command parameter
# on first start (and again whenever the parameter value changes). The
# command can install deps, `docker compose up -d` services, and seed
# demo data - docker works via the mounted host socket (DooD).
resource "coder_script" "project_setup" {
  count        = data.coder_workspace.me.start_count
  agent_id     = coder_agent.main.id
  display_name = "Project Setup"
  run_on_start = true
  script       = templatefile("${path.module}/scripts/project-setup.sh.tftpl", {
    setup_command = data.coder_parameter.setup_command.value
  })
}

resource "docker_volume" "home_volume" {
  name = "coder-${data.coder_workspace.me.id}-home"
  # Protect the volume from being deleted due to changes in attributes.
  lifecycle {
    ignore_changes = all
  }
  # Add labels in Docker to keep track of orphan resources.
  labels {
    label = "coder.owner"
    value = data.coder_workspace_owner.me.name
  }
  labels {
    label = "coder.owner_id"
    value = data.coder_workspace_owner.me.id
  }
  labels {
    label = "coder.workspace_id"
    value = data.coder_workspace.me.id
  }
  # This field becomes outdated if the workspace is renamed but can
  # be useful for debugging or cleaning out dangling volumes.
  labels {
    label = "coder.workspace_name_at_creation"
    value = data.coder_workspace.me.name
  }
}

resource "docker_container" "workspace" {
  count = data.coder_workspace.me.start_count
  image = local.workspace_image

  # gVisor sandbox (default) or plain container runtime — see the
  # workspace_runtime variable. NEVER add `privileged = true` here:
  # runsc rejects it and privileged mode defeats the sandbox.
  runtime = data.coder_parameter.workspace_runtime.value

  # Uses lower() to avoid Docker restriction on container names.
  name = "coder-${data.coder_workspace_owner.me.name}-${lower(data.coder_workspace.me.name)}"
  # Hostname makes the shell more user friendly: coder@my-workspace:~$
  hostname = data.coder_workspace.me.name
  # Use the docker gateway if the access URL is 127.0.0.1
  command = ["sh", "-c", replace(coder_agent.main.init_script, "/localhost|127\\.0\\.0\\.1/", "host.docker.internal")]
  env = [
    "CODER_AGENT_TOKEN=${coder_agent.main.token}"
  ]
  host {
    host = "host.docker.internal"
    ip   = "host-gateway"
  }

  # Workspace home volume persists user data across workspace restarts.
  volumes {
    container_path = "/home/coder"
    volume_name    = docker_volume.home_volume.name
    read_only      = false
  }

  # Docker-outside-of-Docker over TLS: the daemon's client certs are
  # mounted read-only; the startup script points the docker CLI at
  # tcp://<tailscale-ip>:2376 (gVisor can't relay unix-socket connects,
  # so a socket bind-mount does NOT work).
  volumes {
    container_path = "/certs/docker"
    host_path      = var.docker_cert_dir
    read_only      = true
  }

  # Add labels in Docker to keep track of orphan resources.
  labels {
    label = "coder.owner"
    value = data.coder_workspace_owner.me.name
  }
  labels {
    label = "coder.owner_id"
    value = data.coder_workspace_owner.me.id
  }
  labels {
    label = "coder.workspace_name"
    value = data.coder_workspace.me.name
  }
}
