terraform {
  required_providers {
    coder = {
      source = "coder/coder"
    }
    docker = {
      source = "kreuzwerker/docker"
    }
  }
}

locals {
  username = data.coder_workspace_owner.me.name

  # Workspace image with Node.js and the docker CLI preinstalled.
  # Standard: DooD over TLS to the shared isolated daemon
  # (workspace-docker dind on <tailscale-ip>:2376). No bind-mounted
  # socket — gVisor cannot relay unix-socket connects.
  # Default tooling like npm, python, uv, gh (GitHub CLI), go, and rust is
  # ensured at workspace start via startup_script (installed if missing).
  workspace_image = "codercom/enterprise-node:ubuntu"

  has_repo           = data.coder_parameter.repo_url.value != ""
  repo_folder        = try(module.git-clone[0].folder_name, "")
  code_server_folder = local.has_repo ? "/home/coder/${local.repo_folder}" : "/home/coder"
}

# ------------------------------------------------------------------
# Docker daemon endpoint selection.
#
# LOCAL workspaces: leave docker_host empty (""). The provider falls
# back to the local Unix socket (/var/run/docker.sock) on the machine
# running the build — i.e. the Coder server's Docker daemon.
#
# REMOTE workspaces: set
#   docker_host     = "tcp://<tailscale-ip>:2376"
#   docker_ca       = contents of the remote's ca.pem
#   docker_cert     = contents of the remote's cert.pem
#   docker_key      = contents of the remote's key.pem
#
# The cert material is passed as PEM CONTENTS via these variables — no
# files need to be mounted into the Coder container. Marked sensitive so
# they're encrypted at rest and never shown in the UI.
# ------------------------------------------------------------------

variable "docker_host" {
  default     = ""
  description = "(Optional) Docker daemon URI. Empty = local Unix socket. Standard remote: tcp://<tailscale-ip>:2376 (shared isolated dind — see README Prerequisites). Host-daemon alternative: tcp://<ts-ip>:2378 (see G14)."
  type        = string
}

variable "docker_ca" {
  default     = ""
  description = "(Remote only) Docker CA certificate PEM contents"
  type        = string
  sensitive   = true
}

variable "docker_cert" {
  default     = ""
  description = "(Remote only) Docker client certificate PEM contents"
  type        = string
  sensitive   = true
}

variable "docker_key" {
  default     = ""
  description = "(Remote only) Docker client private key PEM contents"
  type        = string
  sensitive   = true
}

# ------------------------------------------------------------------
# Workspace runtime (per-workspace choice).
#
# runsc = gVisor sandbox (default, but see G13). Each workspace gets a
# user-space kernel boundary: syscalls are intercepted by the Sentry.
# No privileged mode, no nested daemons, no kernel modules.
# On unified cgroup v2 hosts, runsc cannot run inside the shared dind
# (G13) — use runc there, or point the template at the host daemon
# (tcp://<ts-ip>:2378, runsc on the host).
#
# runc = plain container runtime (recommended for the shared isolated
# daemon). Use for workspaces that need full tool compatibility
# (sudo, tar-based installers, interactive TUIs — e.g. opencode TUI
# never renders under gVisor — https://github.com/sst/opencode/issues/29802;
# headless `opencode run` works fine on runsc).
# The daemon must have the chosen runtime registered.
# ------------------------------------------------------------------

data "coder_parameter" "workspace_runtime" {
  type         = "string"
  name         = "workspace_runtime"
  display_name = "Workspace Runtime"
  description  = "runsc (gVisor sandbox) or runc (plain container). Choose runc if an interactive TUI fails to render under gVisor (e.g. opencode issue #29802)."
  default      = "runsc"
  mutable      = true

  option {
    name  = "runsc (gVisor sandbox)"
    value = "runsc"
  }
  option {
    name  = "runc (plain container)"
    value = "runc"
  }

  validation {
    regex = "^(runsc|runc)$"
    error = "workspace_runtime must be 'runsc' or 'runc'."
  }
}

# ------------------------------------------------------------------
# Docker access inside the workspace (DooD over TLS).
#
# gVisor CANNOT relay connections through bind-mounted unix sockets, so
# the docker CLI in the workspace talks to the daemon over TLS instead:
#   DOCKER_HOST=tcp://<tailscale-ip>:2376
#   DOCKER_TLS_VERIFY=1, DOCKER_CERT_PATH=<mount point>
#
# The daemon's client certs (ca.pem/cert.pem/key.pem) must exist at
# docker_cert_dir; that directory is mounted read-only into the
# workspace.
# Standard (recommended): shared isolated dind — certs at /certs/client
# inside workspace-docker (generated by docker:dind), mounted from the
# host path that bind-mounts that volume (or staged). Host-daemon
# alternative: stage the client certs at e.g. /home/josh/coder-tls/<remote>/.
#
# IMPORTANT: docker_enabled=false removes ALL docker access from the
# workspace — no cert mount, no DOCKER_* env, the docker CLI cannot
# reach the host daemon. Use it for templates where the developer
# should NOT see (or touch) the host's containers.
# ------------------------------------------------------------------

variable "docker_enabled" {
  default     = true
  description = "Whether workspaces get Docker access to the host daemon (DooD over TLS). false = no cert mount and no DOCKER_* env — the docker CLI inside the workspace cannot connect. Set per template: enable on trusted dev templates, disable on locked-down ones."
  type        = bool
}

variable "docker_cert_dir" {
  default     = "/certs/client"
  description = "Host path of the daemon's client TLS material (ca.pem, cert.pem, key.pem), mounted read-only into the workspace so the docker CLI can talk to the daemon over TLS (DooD). Ignored when docker_enabled is false."
  type        = string
}

data "coder_parameter" "enable_docker" {
  type         = "bool"
  name         = "enable_docker"
  display_name = "Enable Docker"
  description  = "Whether this workspace gets Docker access (DooD over TLS) to the shared daemon. Disable for a plain dev container. Requires the template to have been pushed with docker_enabled=true and a docker_host."
  default      = true
  mutable      = true
}

# ------------------------------------------------------------------
# Template-level startup command.
#
# Baked into the agent startup script (applies to ALL workspaces from
# this template). Runs FIRST, before any per-workspace setup (the
# setup_command parameter / project-setup script). Set per template at
# push time:
#   coder templates push <name> ... --var startup_command="..."
# Empty = no-op.
# ------------------------------------------------------------------

variable "startup_command" {
  default     = ""
  description = "(Template-level) Shell command baked into every workspace's agent startup. Runs first, before per-workspace setup. Empty = no-op."
  type        = string
}

# ------------------------------------------------------------------
# Resource limits (per workspace).
#
# Enforced by the kernel via cgroups — works identically for runc and
# runsc (the runsc Sentry + Gofer count toward the workspace's limits,
# since they run in the same cgroup).
#   - memory: hard limit. The workspace is OOM-killed if it exceeds it.
#   - cpu:    soft-ish throttle (cgroup CPU quota), never killed.
# ------------------------------------------------------------------

variable "workspace_memory_gb" {
  default     = 2
  description = "Hard memory limit per workspace in GB (e.g. 2, 4, 1.5). Exceeding it OOM-kills the workspace; includes runsc Sentry/Gofer overhead."
  type        = number
}

variable "workspace_cpus" {
  default     = "2"
  description = "CPU limit per workspace in cores (throttled, not killed). e.g. '2', '1.5'."
  type        = string
}

data "coder_parameter" "repo_url" {
  type         = "string"
  name         = "repo_url"
  display_name = "Git Repository"
  description  = "Enter the URL of a Git repository to clone. If provided, the workspace will clone it. Leave empty to skip cloning and work in the home directory."
  default      = ""
  mutable      = true
}

data "coder_parameter" "new_branch" {
  type         = "string"
  name         = "new_branch"
  display_name = "New Branch Name"
  description  = "Optional: after cloning, checkout or create this branch. If the branch does not exist, it will be created from HEAD."
  default      = ""
  mutable      = true
}

data "coder_parameter" "setup_command" {
  type         = "string"
  name         = "setup_command"
  display_name = "Setup Command"
  description  = "Optional: shell command run once on first workspace start to prepare the project - install dependencies, docker compose up services, seed demo data. Example: 'make dev' or './scripts/setup.sh'. Runs as the workspace user; docker works via the mounted daemon socket. Change this parameter to trigger a re-run on the next start."
  default      = ""
  mutable      = true
}

provider "docker" {
  host = var.docker_host != "" ? var.docker_host : null

  ca_material   = var.docker_ca != "" ? var.docker_ca : null
  cert_material = var.docker_cert != "" ? var.docker_cert : null
  key_material  = var.docker_key != "" ? var.docker_key : null
}

data "coder_provisioner" "me" {}
data "coder_workspace" "me" {}
data "coder_workspace_owner" "me" {}

resource "coder_agent" "main" {
  arch           = data.coder_provisioner.me.arch
  os             = "linux"
  startup_script = <<-EOT
    set -e

    # Template-level startup command (applies to ALL workspaces from this
    # template). Runs first, before per-workspace setup. Set via the
    # template variable startup_command; empty = no-op.
    %{ if var.startup_command != "" }
    echo "Running template startup command..."
    ${var.startup_command}
    %{ endif }

    # Prepare user home with default files on first start.
    if [ ! -f ~/.init_done ]; then
      cp -rT /etc/skel ~
      touch ~/.init_done
    fi

    # Ensure GitHub CLI (gh) is installed — required by default like npm, python, uv, go, rust.
    # gVisor (runsc) does not support sudo/setuid, so apt + sudo will fail there;
    # the binary fallback to $HOME/.local/bin works without sudo and is the primary
    # path for runsc workspaces. On runc workspaces sudo works and apt is tried first.
    if ! command -v gh >/dev/null 2>&1; then
      echo "Installing GitHub CLI (gh)..."
      if command -v apt-get >/dev/null 2>&1 && sudo -n true 2>/dev/null; then
        echo "Attempting apt install for gh..."
        sudo mkdir -p /usr/share/keyrings 2>/dev/null || true
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg 2>/dev/null && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg 2>/dev/null || true
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null 2>/dev/null || true
        sudo apt-get update -qq 2>/dev/null && sudo apt-get install -y gh -qq 2>/dev/null && echo "gh installed via apt" || echo "apt install failed, trying binary..."
      fi
      if ! command -v gh >/dev/null 2>&1; then
        echo "Installing gh via binary download..."
        mkdir -p $HOME/.local/bin
        GH_VERSION=$(curl -fsSL https://api.github.com/repos/cli/cli/releases/latest 2>/dev/null | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/' 2>/dev/null || echo "2.78.0")
        ARCH=$(uname -m); case $ARCH in x86_64) ARCH="amd64" ;; aarch64|arm64) ARCH="arm64" ;; *) ARCH="amd64" ;; esac
        curl -fsSL "https://github.com/cli/cli/releases/download/v"$GH_VERSION"/gh_"$GH_VERSION"_linux_"$ARCH".tar.gz" -o /tmp/gh.tar.gz 2>/dev/null && tar -xzf /tmp/gh.tar.gz -C /tmp 2>/dev/null && mv /tmp/gh_"$GH_VERSION"_linux_"$ARCH"/bin/gh $HOME/.local/bin/gh 2>/dev/null && chmod +x $HOME/.local/bin/gh 2>/dev/null && rm -rf /tmp/gh.tar.gz /tmp/gh_"$GH_VERSION"_linux_"$ARCH" 2>/dev/null && echo "gh installed to $HOME/.local/bin/gh" || echo "Warning: gh binary install failed"
        export PATH="$HOME/.local/bin:$PATH"
        grep -q 'HOME/.local/bin' $HOME/.bashrc 2>/dev/null || echo 'export PATH="$HOME/.local/bin:$PATH"' >> $HOME/.bashrc 2>/dev/null || true
      fi
      if command -v gh >/dev/null 2>&1; then
        echo "gh installed: $(gh --version 2>/dev/null | head -n1)"
      else
        echo "Warning: gh installation failed - check network or install manually"
      fi
    else
      echo "gh already installed: $(gh --version 2>/dev/null | head -n1)"
    fi
    export PATH="$HOME/.local/bin:$PATH"

    # Ensure uv is installed — Python package manager (astral.sh/uv)
    # gVisor note: pipx and standalone installer both work without sudo; binary to $HOME/.local/bin is primary.
    if ! command -v uv >/dev/null 2>&1; then
      echo "Installing uv..."
      if command -v pipx >/dev/null 2>&1; then
        pipx install uv 2>/dev/null && echo "uv installed via pipx" || echo "pipx install failed, trying standalone..."
      fi
      if ! command -v uv >/dev/null 2>&1; then
        echo "Installing uv via standalone installer..."
        mkdir -p $HOME/.local/bin 2>/dev/null || true
        curl -LsSf https://astral.sh/uv/install.sh 2>/dev/null | sh 2>/dev/null && echo "uv installed via astral.sh" || echo "Warning: uv standalone install failed"
        export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$PATH"
        grep -q 'HOME/.local/bin' $HOME/.bashrc 2>/dev/null || echo 'export PATH="$HOME/.local/bin:$PATH"' >> $HOME/.bashrc 2>/dev/null || true
      fi
      if command -v uv >/dev/null 2>&1; then
        echo "uv installed: $(uv --version 2>/dev/null | head -n1)"
      else
        echo "Warning: uv installation failed - check network or install manually"
      fi
    else
      echo "uv already installed: $(uv --version 2>/dev/null | head -n1)"
    fi
    export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$PATH"

    # Ensure Go is installed — https://go.dev
    # gVisor note: tar extraction to $HOME/.local/go works without sudo; apt fallback only for runc.
    if ! command -v go >/dev/null 2>&1; then
      echo "Installing Go..."
      mkdir -p $HOME/.local/bin $HOME/.local/go 2>/dev/null || true
      GO_VERSION=$(curl -fsSL https://go.dev/VERSION?m=text 2>/dev/null | head -n1 | sed 's/go//' 2>/dev/null || echo "1.24.3")
      ARCH=$(uname -m); case $ARCH in x86_64) ARCH="amd64" ;; aarch64|arm64) ARCH="arm64" ;; *) ARCH="amd64" ;; esac
      echo "Downloading Go v"$GO_VERSION" for linux_"$ARCH"..."
      curl -fsSL "https://go.dev/dl/go"$GO_VERSION".linux_"$ARCH".tar.gz" -o /tmp/go.tar.gz 2>/dev/null && tar -xzf /tmp/go.tar.gz -C /tmp 2>/dev/null && rm -rf $HOME/.local/go 2>/dev/null && mv /tmp/go $HOME/.local/go 2>/dev/null && rm -rf /tmp/go.tar.gz 2>/dev/null && echo "Go installed to $HOME/.local/go" || echo "Go tarball install failed, trying apt..."
      if ! command -v go >/dev/null 2>&1 && [ -x "$HOME/.local/go/bin/go" ]; then
        export PATH="$HOME/.local/go/bin:$PATH"
        grep -q 'HOME/.local/go/bin' $HOME/.bashrc 2>/dev/null || echo 'export PATH="$HOME/.local/go/bin:$PATH"' >> $HOME/.bashrc 2>/dev/null || true
      fi
      if ! command -v go >/dev/null 2>&1 && command -v apt-get >/dev/null 2>&1 && sudo -n true 2>/dev/null; then
        echo "Attempting apt install for Go..."
        sudo apt-get update -qq 2>/dev/null && sudo apt-get install -y golang-go -qq 2>/dev/null && echo "Go installed via apt" || echo "apt Go install failed"
      fi
      export PATH="$HOME/.local/go/bin:$HOME/go/bin:$PATH"
      if command -v go >/dev/null 2>&1; then
        echo "Go installed: $(go version 2>/dev/null | head -n1)"
      else
        echo "Warning: Go installation failed - check network or install manually"
      fi
    else
      echo "Go already installed: $(go version 2>/dev/null | head -n1)"
    fi
    export PATH="$HOME/.local/go/bin:$HOME/go/bin:$PATH"

    # Ensure Rust is installed — https://rustup.rs
    # gVisor note: rustup installs to $HOME/.cargo without sudo; works on both runc and runsc.
    if ! command -v rustc >/dev/null 2>&1 && ! command -v cargo >/dev/null 2>&1; then
      echo "Installing Rust (rustup)..."
      mkdir -p $HOME/.cargo/bin 2>/dev/null || true
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs 2>/dev/null | sh -s -- -y --no-modify-path --default-toolchain stable --profile minimal 2>/dev/null && echo "Rust installed via rustup" || echo "Warning: rustup install failed"
      export PATH="$HOME/.cargo/bin:$PATH"
      grep -q 'HOME/.cargo/bin' $HOME/.bashrc 2>/dev/null || echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> $HOME/.bashrc 2>/dev/null || true
      if command -v rustc >/dev/null 2>&1; then
        echo "Rust installed: $(rustc --version 2>/dev/null | head -n1) $(cargo --version 2>/dev/null | head -n1)"
      else
        echo "Warning: Rust installation failed - check network or install manually"
      fi
    else
      echo "Rust already installed: $(rustc --version 2>/dev/null | head -n1) $(cargo --version 2>/dev/null | head -n1)"
    fi
    export PATH="$HOME/.cargo/bin:$PATH"
    # Ensure all toolchain bins are on PATH for this session
    export PATH="$HOME/.local/bin:$HOME/.local/go/bin:$HOME/go/bin:$HOME/.cargo/bin:$PATH"

    # Add any commands that should be executed at workspace startup
    # (e.g. install requirements, start a program, etc) here.
  EOT
  # NOTE: no shutdown_script by design. A previous version ran
  # `docker system prune -a -f` + `sudo service docker stop` at shutdown.
  # That is only safe while the workspace's docker CLI talks to its OWN
  # nested daemon. Once a host docker socket is mounted into workspaces
  # (DooD), a shutdown prune would wipe HOST containers/images
  # (Coolify, n8n, Ghost, Postgres, ...). Never run daemon-wide docker
  # cleanup from a workspace.

  # These environment variables allow you to make Git commits right away after creating a
  # workspace. Note that they take precedence over configuration defined in ~/.gitconfig!
  # You can remove this block if you'd prefer to configure Git manually or using
  # dotfiles. (see docs/dotfiles.md)
  #
  # In remote mode (docker_host set) the docker CLI is pointed at the
  # daemon over TLS (DooD) — gVisor cannot relay unix-socket connects,
  # so the socket mount does not work. Certs are mounted at
  # /certs/docker (see docker_cert_dir). All of this is skipped when
  # docker_enabled is false: the workspace has no docker access at all.
  env = merge(
    {
      GIT_AUTHOR_NAME     = coalesce(data.coder_workspace_owner.me.full_name, data.coder_workspace_owner.me.name)
      GIT_AUTHOR_EMAIL    = "${data.coder_workspace_owner.me.email}"
      GIT_COMMITTER_NAME  = coalesce(data.coder_workspace_owner.me.full_name, data.coder_workspace_owner.me.name)
      GIT_COMMITTER_EMAIL = "${data.coder_workspace_owner.me.email}"
    },
    var.docker_host != "" && var.docker_enabled && data.coder_parameter.enable_docker.value ? {
      DOCKER_HOST       = "tcp://host.docker.internal:${split(":", var.docker_host)[2]}"
      DOCKER_TLS_VERIFY = "1"
      DOCKER_CERT_PATH  = "/certs/docker"
    } : {}
  )

  # The following metadata blocks are optional. They are used to display
  # information about your workspace in the dashboard. You can remove them
  # if you don't want to display any information.
  metadata {
    display_name = "CPU Usage"
    key          = "0_cpu_usage"
    script       = "coder stat cpu"
    interval     = 10
    timeout      = 1
  }

  metadata {
    display_name = "RAM Usage"
    key          = "1_ram_usage"
    script       = "coder stat mem"
    interval     = 10
    timeout      = 1
  }

  metadata {
    display_name = "Home Disk"
    key          = "3_home_disk"
    script       = "coder stat disk --path $${HOME}"
    interval     = 60
    timeout      = 1
  }

  metadata {
    display_name = "CPU Usage (Host)"
    key          = "4_cpu_usage_host"
    script       = "coder stat cpu --host"
    interval     = 10
    timeout      = 1
  }

  metadata {
    display_name = "Memory Usage (Host)"
    key          = "5_mem_usage_host"
    script       = "coder stat mem --host"
    interval     = 10
    timeout      = 1
  }

  metadata {
    display_name = "Load Average (Host)"
    key          = "6_load_host"
    # get load avg scaled by number of cores
    script   = <<EOT
      echo "`cat /proc/loadavg | awk '{ print $1 }'` `nproc`" | awk '{ printf "%0.2f", $1/$2 }'
    EOT
    interval = 60
    timeout  = 1
  }

  metadata {
    display_name = "Swap Usage (Host)"
    key          = "7_swap_host"
    script       = <<EOT
      free -b | awk '/^Swap/ { printf("%.1f/%.1f", $3/1024.0/1024.0/1024.0, $2/1024.0/1024.0/1024.0) }'
    EOT
    interval     = 10
    timeout      = 1
  }
}

# See https://registry.coder.com/modules/coder/code-server
module "code-server" {
  count    = data.coder_workspace.me.start_count
  source   = "registry.coder.com/coder/code-server/coder"
  version  = "1.5.0"
  agent_id = coder_agent.main.id
  folder     = local.code_server_folder
  extensions = [
    "dracula-theme.theme-dracula",
    "cweijan.vscode-database-client2",
    "ms-vscode.live-server",
    "mathematic.vscode-pdf"
  ]
}

# See https://registry.coder.com/modules/coder/git-clone
module "git-clone" {
  count    = data.coder_workspace.me.start_count * (local.has_repo ? 1 : 0)
  source   = "registry.coder.com/coder/git-clone/coder"
  agent_id = coder_agent.main.id
  url      = data.coder_parameter.repo_url.value
  base_dir = "~"
  # This ensures that the latest non-breaking version of the module gets
  # downloaded, you can also pin the module version to prevent breaking
  # changes in production.
  version = "~> 2.0"
}

# Enables git authentication for cloning PRIVATE repositories.
#
# Without this, cloning a private repo fails with:
#   fatal: unable to access 'https://github.com/<owner>/<repo>.git/':
#   The requested URL returned error: 403
# ("Write access to repository not granted").
#
# This requires a Git provider configured in Coder:
#   Admin -> External Auth -> "GitHub" -> enabled for this template.
# On first workspace start Coder then prompts the user to connect GitHub,
# and the git-clone module uses that token to clone.
#
# Leave the repo_url parameter EMPTY to skip cloning entirely (no prompt).
data "coder_external_auth" "github" {
  id = "github"
}

# One-time per-workspace project setup: runs the setup_command parameter
# on first start (and again whenever the parameter value changes). The
# command can install deps, `docker compose up -d` services, and seed
# demo data - docker works via the mounted host socket (DooD).
resource "coder_script" "project_setup" {
  count        = data.coder_workspace.me.start_count
  agent_id     = coder_agent.main.id
  display_name = "Project Setup"
  run_on_start = true
  script       = templatefile("${path.module}/scripts/project-setup.sh.tftpl", {
    setup_command = data.coder_parameter.setup_command.value
  })
}

resource "docker_volume" "home_volume" {
  name = "coder-${data.coder_workspace.me.id}-home"
  # Protect the volume from being deleted due to changes in attributes.
  lifecycle {
    ignore_changes = all
  }
  # Add labels in Docker to keep track of orphan resources.
  labels {
    label = "coder.owner"
    value = data.coder_workspace_owner.me.name
  }
  labels {
    label = "coder.owner_id"
    value = data.coder_workspace_owner.me.id
  }
  labels {
    label = "coder.workspace_id"
    value = data.coder_workspace.me.id
  }
  # This field becomes outdated if the workspace is renamed but can
  # be useful for debugging or cleaning out dangling volumes.
  labels {
    label = "coder.workspace_name_at_creation"
    value = data.coder_workspace.me.name
  }
}

resource "docker_container" "workspace" {
  count = data.coder_workspace.me.start_count
  image = local.workspace_image

  # gVisor sandbox (default) or plain container runtime — see the
  # workspace_runtime variable. NEVER add `privileged = true` here:
  # runsc rejects it and privileged mode defeats the sandbox.
  runtime = data.coder_parameter.workspace_runtime.value

  # Resource limits (cgroup-enforced; same for runc and runsc).
  memory      = var.workspace_memory_gb * 1024 * 1024 * 1024
  memory_swap = var.workspace_memory_gb * 1024 * 1024 * 1024 # no swap for workspaces
  cpus        = var.workspace_cpus

  # Uses lower() to avoid Docker restriction on container names.
  name = "coder-${data.coder_workspace_owner.me.name}-${lower(data.coder_workspace.me.name)}"
  # Hostname makes the shell more user friendly: coder@my-workspace:~$
  hostname = data.coder_workspace.me.name
  # Use the docker gateway if the access URL is 127.0.0.1
  command = ["sh", "-c", replace(coder_agent.main.init_script, "/localhost|127\\.0\\.0\\.1/", "host.docker.internal")]
  env = [
    "CODER_AGENT_TOKEN=${coder_agent.main.token}"
  ]
  host {
    host = "host.docker.internal"
    ip   = "host-gateway"
  }

  # Workspace home volume persists user data across workspace restarts.
  volumes {
    container_path = "/home/coder"
    volume_name    = docker_volume.home_volume.name
    read_only      = false
  }

  # Docker-outside-of-Docker over TLS: the daemon's client certs are
  # mounted read-only; the agent env points the docker CLI at
  # tcp://<tailscale-ip>:2376 (gVisor can't relay unix-socket connects,
  # so a socket bind-mount does NOT work).
  #
  # Skipped when docker_enabled is false or docker_cert_dir is empty
  # (""): the workspace container runs, but docker-in-workspace is
  # unavailable.
  dynamic "volumes" {
    for_each = var.docker_enabled && var.docker_host != "" && var.docker_cert_dir != "" && data.coder_parameter.enable_docker.value ? [1] : []
    content {
      container_path = "/certs/docker"
      host_path      = var.docker_cert_dir
      read_only      = true
    }
  }

  # Add labels in Docker to keep track of orphan resources.
  labels {
    label = "coder.owner"
    value = data.coder_workspace_owner.me.name
  }
  labels {
    label = "coder.owner_id"
    value = data.coder_workspace_owner.me.id
  }
  labels {
    label = "coder.workspace_name"
    value = data.coder_workspace.me.name
  }
}
